name:                ely
version:             0.1.0.0
github:              "thomasjm/ely"
license:             BSD3
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Generating simulated requests to a contextual combinatorial bandit
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ely#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ely-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - binary
    - bytestring
    - convertible
    - cookie
    - ely
    - HTTP
    - interpolate
    - mwc-random
    - random-fu
    - tagsoup
    - uri-encode

tests:
  ely-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ely
